### ISSUE TITLE
spark-local-dirs are duplicate / ignored in example yaml

### ISSUE THREAD

**Issue by hopper-signifyd** [aws-samples/eks-spark-benchmark#7]
Hello,

I tried running the example found here: `examples/spark-pi-hostpath.yaml`

Running the initial job resulted in this exception:
```
{FAILED failed to run spark-submit for SparkApplication default/spark-pi-hostpath: Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://xxx/api/v1/namespaces/default/pods. Message: Pod "spark-pi-hostpath-driver" is invalid: spec.volumes[1].name: Duplicate value: "spark-local-dir-1". Received status:
Status(apiVersion=v1, code=422, details=StatusDetails(causes[StatusCause(field=spec.volumes[1].name, message=Duplicate value: "spark-local-dir-1", reason=FieldValueDuplicate, additionalProperties={})], group=null, kind=Pod, name=spark-pi-hostpath-driver, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "spark-pi-hostpath-driver" is invalid: spec.volumes[1].name: Duplicate value: "spark-local-dir-1", metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
```

I realized this was probably happening because `spark-local-dir-1` is getting mapped elsewhere as an `emptyDir`, so I commented that out and re-ran the job. However, it doesn't look like these directories are actually getting registered as local dirs as I'm seeing this in the environment variables for the pod:
`SPARK_LOCAL_DIRS:           /var/data/spark-0bffb011-4c7f-4381-820d-3c110c4dedce`

This should include the `spark-local-dir-` mountPath values.

Also, Spark cleans up any local dirs after the job is finished, and it's not cleaning up the local dirs that we tried to mount:
```
INFO ShutdownHookManager: Deleting directory /tmp/spark-20f8ab1a-bb2e-465e-b7c4-2edf3059bd7d                                                                                                                              │
INFO ShutdownHookManager: Deleting directory /var/data/spark-0bffb011-4c7f-4381-820d-3c110c4dedce/spark-e0dd2bbd-f41b-4594-8026-3aae93a2c1a6
```

YAML (with the commented out `spark-local-dir-1` mapping):
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-hostpath
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "seedjeffwan/spark:v2.4.5"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.5.jar"
  arguments:
    - "10000"
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
  volumes:
    # - name: "spark-local-dir-1"
    #   hostPath:
    #     path: "/tmp/mnt-1"
    - name: "spark-local-dir-2"
      hostPath:
        path: "/tmp/mnt-2"
    - name: "spark-local-dir-3"
      hostPath:
        path: "/tmp/mnt-3"
  driver:
    cores: 1
    coreLimit: "1024m"
    memory: "512m"
    labels:
      version: 2.4.5
    serviceAccount: spark
    volumeMounts:
      # - name: "spark-local-dir-1"
      #   mountPath: "/tmp/mnt-1"
      - name: "spark-local-dir-2"
        mountPath: "/tmp/mnt-2"
      - name: "spark-local-dir-3"
        mountPath: "/tmp/mnt-3"
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 2.4.5
    volumeMounts:
      # - name: "spark-local-dir-1"
      #   mountPath: "/tmp/mnt-1"
      - name: "spark-local-dir-2"
        mountPath: "/tmp/mnt-2"
      - name: "spark-local-dir-3"
        mountPath: "/tmp/mnt-3"
```
